### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by Tlosbpy** [zhangce01/DualAdapter#1]
Hello author, due to my poor knowledge of algorithms and limited ability to download datasets，after I successfully run the _extract_features.py_ with only class 5 datasets（"caltech101", 'dtd', 'food101', 'oxford_flowers', 'oxford_pets'）, this error occurs when running _main.py_ in the next step.
The code in main.py has not changed, I‘d like to ask if this error is due to the problem of insufficient datasets or the problem of using the local model?

**The error:**
Traceback (most recent call last):
  File "D:\papercode\DualAdapter_main\main.py", line 326, in <module>
    main()
  File "D:\papercode\DualAdapter_main\main.py", line 266, in main
    assert (os.path.exists(args.config))
  File "E:\Anaconda\envs\AD\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Here are my other changes to the code in _extract_features.py_ for your reference:**
`        for k in k_shot:
            
            random.seed(1)
            torch.manual_seed(1)
            
            cfg['shots'] = k
            if set == 'imagenet':
                dataset = ImageNet(cfg['root_path'], cfg['shots'], preprocess)
                val_loader = torch.utils.data.DataLoader(dataset.test, batch_size=16, num_workers=2, shuffle=False)
                train_loader_cache = torch.utils.data.DataLoader(dataset.train, batch_size=16, num_workers=2, shuffle=False)
            else:   
                dataset = build_dataset(set, data_path, k)
                val_loader = build_data_loader(data_source=dataset.val, batch_size=16, is_train=False, tfm=preprocess, shuffle=False)
                test_loader = build_data_loader(data_source=dataset.test, batch_size=16, is_train=False, tfm=preprocess, shuffle=False)

                train_tranform = transforms.Compose([
                    transforms.RandomResizedCrop(size=224, scale=(0.5, 1), interpolation=transforms.InterpolationMode.BICUBIC),
                    transforms.RandomHorizontalFlip(p=0.5),
                    transforms.ToTensor(),
                    transforms.Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))])
                train_loader_cache = build_data_loader(data_source=dataset.train_x, batch_size=16, tfm=train_tranform, is_train=True, shuffle=False)`

**Comment by zhangce01** [comment]
Have you successfully overcome that? Sorry but I've never encountered this issue on my end.
